### ISSUE TITLE
TopSuperIssue Top Méga Gros

### ISSUE THREAD

**Issue by Christophe-IAD** [Christophe-IAD/SF-Sandbox#1]
The ultimate mega combo comment de la mort qui tue Chuck Norris

**Comment by Christophe-IAD** [comment]
Ils auraient peut-être put faire des outils comme ça là

**Comment by Ikimasoft** [comment]
#Agad latele vizion et pis dort

**Comment by Ikimasoft** [comment]
biiiiitch
---------
